apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gulimall-coupon
  name: gulimall-coupon
  namespace: gulimall
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: gulimall-coupon
  template:
    metadata:
      labels:
        app: gulimall-coupon
    spec:
      containers:
        - name: gulimall-coupon
          image: docker.io/zte020415/gulimall-coupon:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst

---
kind: Service
apiVersion: v1
metadata:
  name: gulimall-coupon
  namespace: gulimall
  labels:
    app: gulimall-coupon
spec:
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
      nodePort: 31003
  selector:
    app: gulimall-coupon
  type: NodePort
  sessionAffinity: None



