spring.thymeleaf.cache=false

gulimall.thread.coreSize=20
gulimall.thread.maxSize=200
gulimall.thread.keepAliveTime=10

# RabbitMQéç½®
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
# èæä¸»æºéç½®
spring.rabbitmq.virtual-host=/
# å¼å¯åéç«¯æ¶æ¯æµè¾¾Brokerç¡®è®¤
spring.rabbitmq.publisher-confirms=true
# å¼å¯åéç«¯æ¶æ¯æµè¾¾Queueç¡®è®¤
spring.rabbitmq.publisher-returns=true
# åªè¦æ¶æ¯æµè¾¾Queueï¼å°±ä¼å¼æ­¥åéä¼ååè°returnfirm
spring.rabbitmq.template.mandatory=true
# æå¨ackæ¶æ¯ï¼ä¸ä½¿ç¨é»è®¤çæ¶è´¹ç«¯ç¡®è®¤
spring.rabbitmq.listener.simple.acknowledge-mode=manual

#æ¯ä»å®ç¸å³çéç½®
alipay.app_id=9021000162660202
alipay.merchant_private_key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCALSpbJYROVD4T+teFdLAWqjv4pQdc+3yhJJuFl4AltPI4WZSdAjFvi5Ooid91VlL8yQG9r/4ipJ8v7xy/f4WbSnkzXI4ldnm9ErkYX9Bl8MjF8wGJpsTrAuNotvaDYxBXMnHDrqjopc52Grvcst3jfzyQKt4ZWxWFSfpCO218ZU7KsMUBn8YOLHCMnzSlvyq/gHlqnyZsPR7507EkC5Uuu//F/8rChhC4KOZ4YGvAxszuJUxjoXC1f2NELRLWs0br2MZ1DYaDeznc2qDuMcgfgNkNeABKr3HMWTAODspfCooZ1205VXA7Dv6obb5N1kwFUfrt3IgQADkr4SCqzrJJAgMBAAECggEAPF6Ja4KBDS9qSZjEd4vc/9/P/S0lCas9KNyID2Sqq5fM2bN/Zm/I/uN7eU7um2I8FelKU6AXjxOAEmCJZrxWHiz2ZrV6EbT6Y4309cDy84Bz35+zorSUXKfwmbpK4tj+skMFCAg0b9bgJgozXyAzl9mumaxHDSQ0P6H3J8i7qXGT47uFhual4HSknyEfnZKzaAKotvGvyRn849O6T6o2fQ44I4E7iKHPqix3tWcLBaVKCDVfoTQj51OEvOp2Dp+O5pDA0crj3Eyfc6Qzl6+WZLz5hcoKi2xcxKm1Lg/n08Tizad20P7uSPK+Nn/zUpfxTzjtHCP8Zw4vQcix3xOeMQKBgQDbYAdircXUUCvPZXs5QRXQEUb/aDER6rQ5DRhBRtDspo8eJM6qqkR7jw6er09ikxmW1UnHft1FnTUk3fE66oHUq02EOe4kXFL6hFelRq7o+Z5GZqxrAYW1YBqtnIVs6yr0bpJkYLw2xWx49mFJ/EWhOrXRGi8//4ya7LcO/92YnQKBgQCVk1rsjeOKudfQ2f7DIbItx/nKvj6eKEwH+MC6J8jgYy4GNxizREJo2QSijVq2jSil+Wm07PZaMM1y3qGINjE30GZwpV3aohklk0AI5nVgk3DqIGian4Aru022jezOiglQQ2f2p4CSyphA3VC0SpJExRngL+BmJzzaRKN3SqxinQKBgQCrf30GldcMTciSEEGu1sTYrkkUrj1+Rj+yQhxuG5CFEQjdheTS4t06wvGo+GBVLa5ZjlBpVzJgk6/SLHfDmUT6Hxkwf6E+Z7avBfsGyCVBGLO1UdsEpGIFEyaIBs8AATDJeg+TzVQWdWyBfAs+ras5ig5Nc+zwWTVwgBHz9e8kuQKBgAzLbA2sHXiyaPmejCJY8Yrk/kMPfv+8ZrSP3LyPxqkbEsbJU72R6zRYzAKzoLzY2k9IRHiLhI82eXyH+r1SFWe21exw2NRo5UnHjMS2Ifg+5HvChfAkEKys+vrQrR8Fw8Iv4ebBcUgdOGTkCZFCh7yGN65rqgBS/uuUz37WzmQpAoGBAKaI/nHNw84GM0XdMASBD5FGjlr4JYpdfmywU8SNxIWfEc9W3YAKC1OWKzhU3XOunoN5HfFNJkunyOm6SymG9KKeG1BcO0J/mXA1CjMbJcQuZArdzoddj/scvfdgGSQ2l5J+5wEIriQxY+mdlVG7Rkh3iBpffAUlMIayDXXjtr49
alipay.alipay_public_key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhgKeSEbHaAay03TTmf7WUh7fRnTb5US3libSJOO/pcvTMyPbNCpDGXo+7dTIBWzX7LLaFOmjEwxIQun8+zbYFQX1YL+K3beXC6d40wEMLLEFh5LBbUFrjtfQ5Lz3T+0WrIIHJk1T00QwcI8aIlBr7emriVbbyctVZ7QsUeuS1atDMlc9sBbRXAktwEuo0O8XA7BVqB6ZfbVHKVYCuTX2TH9ybhOyeBq2allfUFJZRYECT0OCqBBSVzZ32mphMtBjZJliVBx3dkNjD/MJ/zgl2MBVMzEInq8tS6KX3N3Be04cE6y2JHuQTgwJ1EkHaTtbeHqFmogYW+ti5kTRgM1yawIDAQAB
alipay.notify_url=http://p65b9a78.natappfree.cc/payed/notify
alipay.return_url=http://member.gulimall.com/memberOrder.html
alipay.sign_type=RSA2
alipay.charset=utf-8
alipay.gatewayUrl=https://openapi-sandbox.dl.alipaydev.com/gateway.do

#logging.level.

#å¾®ä¿¡ç¸å³éç½®
wx.appId=wxd898fcb01713c658
wx.mchId=1483469312
wx.mchKey=098F6BCD4621D373CADE4E832627B4F6
wx.notifyUrl=http://hjl.mynatapp.cc/pay/notify
wx.returnUrl=http://member.gulimall.com/memberOrder.html

spring.mvc.date-format=yyyy-MM-dd HH:mm:ss


#æå¡è¿½è¸ª
spring.zipkin.base-url=http://zipkin-service.gulimall:9411/
#å³é­æå¡åç°
spring.zipkin.discovery-client-enabled=false
spring.zipkin.sender.type=web
#éç½®éæ ·å¨
spring.sleuth.sampler.probability=1