#服务追踪
#spring.zipkin.base-url=http:/192.168.163.142:9411/
#关闭服务发现
spring.zipkin.discovery-client-enabled=false
spring.zipkin.sender.type=web
#配置采样器
spring.sleuth.sampler.probability=1


endpoint=oss-cn-beijing.aliyuncs.com
accessKeyId = "LTAI4G66cCNM2t7LKE79RaY3"
accessKeySecret = "wd0KVDLCO1vVXq4q9aIPTXY7AP7rdW"